// A WIT file to test the WASM component system

package dotnetcomp:plugin@0.1.0;

interface business-rules {
    record person {
        name: string,
        age: u8,
    }

    variant order-status {
        pending,
        shipped(s32),
        delivered(string)
    }

    enum color {
        red,
        green,
        blue,
    }

    flags allowed-methods {
        get,
        post,
        put,
        delete,
    }

    type persons = list<person>;

    add-s8: func(x :s8, y :s8) -> s8;    
    add-u8: func(x :u8, y :u8) -> u8;
    add-s16: func(x :s16, y :s16) -> s16;
    add-u16: func(x :u16, y :u16) -> u16;
    add-s32: func(x :s32, y :s32) -> s32;
    add-u32: func(x :u32, y :u32) -> u32;
    add-s64: func(x :s64, y :s64) -> s64;
    add-u64: func(x :u64, y :u64) -> u64;
    add-f32: func(x :f32, y :f32) -> f32;
    add-f64: func(x :f64, y :f64) -> f64;
    reverse-list-s32: func(x :list<s32>) -> list<s32>;
    reverse-list-person: func(x: persons) -> persons;
    echo-tuple2: func(x :tuple<f32, s32>) -> tuple<f32, s32>;
    echo-tuple3: func(x :tuple<f32, s32, u8>) -> tuple<f32, s32, u8>;
    echo-record: func(x: person) -> person;
    echo-variant: func(x: order-status) -> order-status;
    echo-enum: func(x: color) -> color;
    echo-option: func(x: option<person>) -> option<person>;
    echo-flags: func(x: allowed-methods) -> allowed-methods;
}

world guest {
    export business-rules;
}

world host {    
}